import Head from "next/head";
import Image from "next/image";
import Navbar from './Navbar';
import HeroHeader from './HeroHeader';
import Feautured from "./Feautured";
import Recommend from "./Recommend";
import Toptraders from "./Toptraders";
const Junn = () => {

  return (
    <>
    <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <HeroHeader/>
        <Feautured/>
        <Recommend/>
        <Toptraders/>
    </>
  );
};

export default Junn;



